### PR TITLE
UPDATED: cookie version is overriden

### PR DESCRIPTION
**Pull request by Aradon267**
Before the update:
```
# npm audit report

cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
No fix available
node_modules/cookie
  @supabase/ssr  *
  Depends on vulnerable versions of cookie
  node_modules/@supabase/ssr

2 low severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

```

After:
```
found 0 vulnerabilities
```

### CODE REVIEW

**Review by YechiamW3 — APPROVED** [review]

**Comment by YechiamW3** [comment]
General remark: we should probably start adding tests, at least to have more certainty on changes like this.

**Comment by Aradon267** [comment]
Can you give an example for a test? I mean this was something that the security advisor suggested

**Comment by YechiamW3** [comment]
> Can you give an example for a test? I mean this was something that the security advisor suggested

I meant generally in the code; if we'd have tests that we rely on we could simply run them and be sure that the change didn't affect anything (generally a good thing; in this particular case I simply can't really tell what the change actually does, unlike actual code change).

**Comment by Aradon267** [comment]
I see. I tried the functionality afterwards and everything seemed to work correctly.
I'm not really familiar with testing websites, how do you add tests?

**Comment by YechiamW3** [comment]
> I see. I tried the functionality afterwards and everything seemed to work correctly. I'm not really familiar with testing websites, how do you add tests?

Yeah that's why I only added as a general remark, and not a comment on the code :)
Testing is usually done using vitest and react-testing-library. We should probably add an issue to gradually add tests.

**Pull request merged**
